export {
  parseBigIntAddr,
  toHex,
  addressesEqual,
  readPositiveInt,
  readNumeric,
  resolveBpRegister,
  extractBasePointerName,
  areKindsCompatible,
  areSizesCompatible,
  rangesOverlap,
  overlapByteCount,
  seedRangeStart,
  seedRangeEnd,
  observationRangeStart,
  observationRangeEnd,
  smallestObservationStart,
  seedOffsetRange,
  isSeedInsideFrameBounds,
  crossesFrameBase,
  formatCanonicalOffsetLabel,
  resolveAbiVisualOffset,
  resolveOffsetBand
} from './stackWorkspaceCore.js';
