export {
  resolveEntryName,
  collectNameCandidates,
  scoreNameCandidate,
  resolveFallbackBucket,
  resolveEntryType,
  normalizeDisplayName,
  isGenericName,
  canonicalSavedBpName,
  normalizeEntryKind,
  normalizeSource,
  resolveSourcePriority,
  classifyTrustedSeedKind,
  classifyObservationSeedKind,
  classifySyntheticObservationKind,
  classifyStructuralHoleFallback,
  resolveRestrictedAbiArgumentName,
  buildEntryKey,
  buildSortIndex,
  compareFrameEntries,
  normalizeFunctionName,
  displayFunctionName,
  sameFunction,
  pickFallbackFunction,
  looksLikeBufferName,
  looksLikeArrayType
} from './stackWorkspaceCore.js';
