export {
  compactCanonicalLayout,
  recoverConcreteObjectExtents,
  collectConcreteObjectExtents,
  collectRecoveredExtentCandidatesFromSnapshot,
  collectRecoveredExtentCandidatesFromAnalysis,
  recoverConcreteObjectExtents as recoverCompactedObjectExtents,
  reclassifyNegativeArgumentSpills,
  compactAdjacentSyntheticBufferEntries,
  shouldMergeAdjacentSyntheticBuffers,
  mergeAdjacentSyntheticBufferEntries,
  shouldSuppressSyntheticObservation,
  fitsStructuralGap,
  compareSeedsForLayout,
  shouldDropWeakStaticSeed,
  shouldCompactSeeds,
  mergeCompactedSeeds,
  seedsConflict,
  shouldAllowNestedSeedCoexistence,
  chooseMoreTrustworthySeed,
  chooseEntryForObservation,
  compareEntryMatch,
  scoreEntryMatch,
  isObservationCompatible,
  allowsContainedBufferObservationMatch,
  finalizeEntryBase,
  finalizeDisplayEntry,
  filterSourceSimpleFrameEntries,
  assignStableFallbackNames,
  buildLogicalArgumentEntries,
  buildNamedLogicalArguments
} from './stackWorkspaceCore.js';
